/**
 * 前世の死因診断
 *
 * ユングの集合的無意識理論とキャンベルの英雄の旅をヒントに、
 * 無意識の好み・恐怖・直感パターンから「前世での最期」を占う。
 * 全てファンタジー風でポジティブ解釈（転生ボーナス付き）。
 *
 * 理論基盤: Jung (1968), Campbell (1949)
 * 7次元 / 25問 / 12タイプ
 */

import type { DiagnosisConfig } from '../diagnosticTypes';

export const deathcauseDiagnosis: DiagnosisConfig = {
  id: 'deathcause',
  title: '前世の死因診断',
  subtitle: '魂に刻まれた記憶を読み解く',
  catchphrase: 'なぜか怖いもの、なぜか惹かれるもの——それは前世の記憶かも',
  description: 'ユングの集合的無意識理論とキャンベルの英雄の旅をヒントに、あなたの無意識の好み・恐怖・直感パターンから「前世での最期」を占います。25問の直感的な質問に答えるだけ。結果はファンタジー風で、前世の死因が今世にもたらした「転生ボーナス」もわかります！',
  emoji: '💀',
  themeColor: '#8B5CF6',
  gradientFrom: '#8B5CF6',
  gradientTo: '#6366F1',
  questionCount: 25,
  estimatedMinutes: 5,

  profileFields: [
    { id: 'gender', label: '性別', type: 'select', options: [
      { value: 'male', label: '男性' },
      { value: 'female', label: '女性' },
      { value: 'other', label: 'その他' },
    ]},
    { id: 'age', label: '年齢', type: 'slider', min: 10, max: 70, defaultValue: 16, unit: '歳' },
  ],

  dimensions: [
    { key: 'fire', label: '火の記憶', color: '#EF4444' },
    { key: 'water', label: '水の記憶', color: '#3B82F6' },
    { key: 'adventure', label: '冒険の記憶', color: '#F59E0B' },
    { key: 'magic', label: '魔法の記憶', color: '#8B5CF6' },
    { key: 'nature', label: '自然の記憶', color: '#22C55E' },
    { key: 'battle', label: '戦いの記憶', color: '#DC2626' },
    { key: 'fate', label: '運命の記憶', color: '#6366F1' },
  ],

  sections: {
    1: '🔮 直感テスト',
    2: '💫 無意識の好み',
    3: '🌀 前世の記憶',
    4: '✨ 魂のパターン',
    5: '🔥 最後の直感',
  },

  questions: [
    { sid: 1, sectionName: '🔮 直感テスト', emoji: '🔮', text: '焚き火の炎をずっと見ていられる方だ', source: 'Jung (1968); Campbell (1949)', weights: [2, 0, 0, 0, 0, 0, 1] },
    { sid: 1, sectionName: '🔮 直感テスト', emoji: '🔮', text: '海や湖の近くにいると、なぜか切ない気持ちになる', source: 'Jung (1968); Campbell (1949)', weights: [0, 2, 0, 0, 1, 0, 0] },
    { sid: 1, sectionName: '🔮 直感テスト', emoji: '🔮', text: '高い場所に立つと、飛んでみたい衝動を感じる', source: 'Jung (1968); Campbell (1949)', weights: [0, 0, 2, 0, 0, 0, 1] },
    { sid: 1, sectionName: '🔮 直感テスト', emoji: '🔮', text: '夜空の星を見ると、「帰りたい」と思うことがある', source: 'Jung (1968); Campbell (1949)', weights: [0, 0, 0, 2, 0, 0, 1] },
    { sid: 1, sectionName: '🔮 直感テスト', emoji: '🔮', text: '森の中にいると安心するが、同時に何かに追われている感覚がある', source: 'Jung (1968); Campbell (1949)', weights: [0, 0, 0, 0, 2, 1, 0] },

    { sid: 2, sectionName: '💫 無意識の好み', emoji: '💫', text: 'ファンタジー作品では「魔法」に関する設定に一番惹かれる', source: 'Jung (1968); Campbell (1949)', weights: [0, 0, 0, 2, 0, 0, 1] },
    { sid: 2, sectionName: '💫 無意識の好み', emoji: '💫', text: '歴史の授業で戦国時代や中世の話に妙にワクワクする', source: 'Jung (1968); Campbell (1949)', weights: [0, 0, 1, 0, 0, 2, 0] },
    { sid: 2, sectionName: '💫 無意識の好み', emoji: '💫', text: '雷や嵐の日、怖いけどどこかテンションが上がる', source: 'Jung (1968); Campbell (1949)', weights: [1, 0, 1, 0, 1, 0, 0] },
    { sid: 2, sectionName: '💫 無意識の好み', emoji: '💫', text: '花や植物に対して、他の人より愛着がある気がする', source: 'Jung (1968); Campbell (1949)', weights: [0, 0, 0, 0, 2, 0, 1] },
    { sid: 2, sectionName: '💫 無意識の好み', emoji: '💫', text: '占いやスピリチュアルな話に、つい引き込まれてしまう', source: 'Jung (1968); Campbell (1949)', weights: [0, 0, 0, 1, 0, 0, 2] },

    { sid: 3, sectionName: '🌀 前世の記憶', emoji: '🌀', text: '初めて行った場所なのに「ここ知ってる」と感じたことがある', source: 'Jung (1968); Campbell (1949)', weights: [0, 0, 1, 1, 0, 0, 2] },
    { sid: 3, sectionName: '🌀 前世の記憶', emoji: '🌀', text: '特定の時代のファッションや建築にやたらと詳しい', source: 'Jung (1968); Campbell (1949)', weights: [0, 0, 1, 0, 0, 1, 1] },
    { sid: 3, sectionName: '🌀 前世の記憶', emoji: '🌀', text: '水の中に潜るのが好き（プール、海、お風呂など）', source: 'Jung (1968); Campbell (1949)', weights: [0, 2, 0, 0, 0, 0, 0] },
    { sid: 3, sectionName: '🌀 前世の記憶', emoji: '🌀', text: '剣や弓など、古い武器に妙に惹かれる', source: 'Jung (1968); Campbell (1949)', weights: [0, 0, 0, 0, 0, 2, 1] },
    { sid: 3, sectionName: '🌀 前世の記憶', emoji: '🌀', text: '同じ夢を何度も見たことがある', source: 'Jung (1968); Campbell (1949)', weights: [0, 0, 0, 1, 0, 0, 2] },

    { sid: 4, sectionName: '✨ 魂のパターン', emoji: '✨', text: '「自分は何か大きな使命がある」と感じることがある', source: 'Jung (1968); Campbell (1949)', weights: [0, 0, 1, 1, 0, 1, 1] },
    { sid: 4, sectionName: '✨ 魂のパターン', emoji: '✨', text: '急に寒気がして「誰かに見られてる」と感じることがある', source: 'Jung (1968); Campbell (1949)', weights: [0, 0, 0, 2, 0, 0, 1] },
    { sid: 4, sectionName: '✨ 魂のパターン', emoji: '✨', text: '動物が自分に寄ってくることが多い', source: 'Jung (1968); Campbell (1949)', weights: [0, 0, 0, 0, 2, 0, 1] },
    { sid: 4, sectionName: '✨ 魂のパターン', emoji: '✨', text: '夕焼けを見ると胸がぎゅっとなる', source: 'Jung (1968); Campbell (1949)', weights: [1, 0, 0, 0, 1, 0, 1] },
    { sid: 4, sectionName: '✨ 魂のパターン', emoji: '✨', text: '誰かを守りたいという気持ちが人一倍強い', source: 'Jung (1968); Campbell (1949)', weights: [0, 0, 0, 0, 0, 2, 0] },

    { sid: 5, sectionName: '🔥 最後の直感', emoji: '🔥', text: '「もう一度やり直せるなら」と考えることがよくある', source: 'Jung (1968); Campbell (1949)', weights: [0, 0, 0, 0, 0, 0, 2] },
    { sid: 5, sectionName: '🔥 最後の直感', emoji: '🔥', text: '火を使う料理（BBQなど）が好きだ', source: 'Jung (1968); Campbell (1949)', weights: [2, 0, 0, 0, 0, 0, 0] },
    { sid: 5, sectionName: '🔥 最後の直感', emoji: '🔥', text: '船や飛行機での移動にワクワクする', source: 'Jung (1968); Campbell (1949)', weights: [0, 1, 2, 0, 0, 0, 0] },
    { sid: 5, sectionName: '🔥 最後の直感', emoji: '🔥', text: '「運命の人」という概念を信じている', source: 'Jung (1968); Campbell (1949)', weights: [0, 0, 0, 1, 0, 0, 2] },
    { sid: 5, sectionName: '🔥 最後の直感', emoji: '🔥', text: '自分の直感は当たると思う', source: 'Jung (1968); Campbell (1949)', weights: [0, 0, 0, 2, 0, 0, 1] },
  ],

  resultTypes: [
    {
      id: 'dragon_fire',
      emoji: '🐉',
      name: '竜の炎に包まれた勇者',
      tag: '伝説の英雄',
      color: '#EF4444',
      description: '前世のあなたは、村を守るために竜と戦った勇敢な英雄でした。最後は竜の炎に包まれましたが、その勇気は伝説として語り継がれています。',
      traits: ['勇敢', '正義感が強い', '火に惹かれる', '英雄的'],
      advice: '【転生ボーナス】前世の勇気が今世にも受け継がれています。困難に立ち向かう不屈の精神があなたの武器です。',
      scoreWeights: [2, -0.5, 1, 0, -0.5, 1.5, 0],
    },
    {
      id: 'ocean_voyage',
      emoji: '🚢',
      name: '大海原に消えた冒険家',
      tag: '伝説の航海者',
      color: '#3B82F6',
      description: '前世のあなたは、未知の大陸を目指して航海した冒険家。嵐の海に飲まれましたが、その冒険心は今も魂に刻まれています。',
      traits: ['冒険心', '自由を愛する', '水に惹かれる', '好奇心旺盛'],
      advice: '【転生ボーナス】前世の冒険心が「新しいことへの好奇心」として開花しています。未知の領域に飛び込む勇気があなたの力です。',
      scoreWeights: [0, 2, 1.5, 0, 0, 0, 0.5],
    },
    {
      id: 'magic_curse',
      emoji: '🔮',
      name: '封印の呪いを受けた魔術師',
      tag: '伝説の魔法使い',
      color: '#8B5CF6',
      description: '前世のあなたは、強大な魔力を持つ魔術師。禁忌の魔法を使い、その代償として永遠の眠りにつきました。',
      traits: ['直感が鋭い', '神秘的', 'スピリチュアル', '知識欲'],
      advice: '【転生ボーナス】前世の魔力が「鋭い直感力」として受け継がれています。人の心を読む力があります。',
      scoreWeights: [0, 0, 0, 2, 0, 0, 1.5],
    },
    {
      id: 'forest_spirit',
      emoji: '🌿',
      name: '森と共に眠った精霊守',
      tag: '森の守り神',
      color: '#22C55E',
      description: '前世のあなたは、聖なる森を守る番人。森が枯れた時、あなたも森と共に眠りにつきました。',
      traits: ['自然を愛する', '穏やか', '動物に好かれる', '繊細'],
      advice: '【転生ボーナス】前世の森との絆が「自然や動物との特別な繋がり」として表れています。',
      scoreWeights: [0, 0, 0, 0.5, 2, 0, 1],
    },
    {
      id: 'battle_hero',
      emoji: '⚔️',
      name: '最後まで戦い抜いた武将',
      tag: '不屈の戦士',
      color: '#DC2626',
      description: '前世のあなたは、仲間を守るために最後まで剣を振るった武将。壮絶な戦いの末に散りましたが、その忠誠心は永遠です。',
      traits: ['忠義に厚い', '仲間思い', '負けず嫌い', '武器に惹かれる'],
      advice: '【転生ボーナス】前世の忠義が「大切な人を守り抜く強い意志」として受け継がれています。',
      scoreWeights: [0.5, 0, 0.5, 0, 0, 2, 0.5],
    },
    {
      id: 'star_fall',
      emoji: '⭐',
      name: '星になった天文学者',
      tag: '星に還った賢者',
      color: '#6366F1',
      description: '前世のあなたは、宇宙の真理を追い求めた天文学者。星を見つめながら静かに旅立ち、自分自身が星の一部になりました。',
      traits: ['知的好奇心', '夜空に惹かれる', 'ロマンチスト', '孤高'],
      advice: '【転生ボーナス】前世の宇宙への探究心が「深い知的好奇心と哲学的思考」として開花しています。',
      scoreWeights: [0, 0, 0, 1.5, 0, 0, 2],
    },
    {
      id: 'poison_queen',
      emoji: '🍷',
      name: '毒杯を受けた王妃',
      tag: '悲劇の貴人',
      color: '#E11D48',
      description: '前世のあなたは、陰謀渦巻く宮廷の王妃。政敵の策略により毒杯を受けましたが、最後まで品位を失いませんでした。',
      traits: ['気品がある', '人を見る目', '疑い深い', '芯が強い'],
      advice: '【転生ボーナス】前世の経験から「人の本心を見抜く力」が備わっています。本質を見極める洞察力が最大の武器です。',
      scoreWeights: [0, 0.5, 0, 1, 0, 0.5, 1.5],
    },
    {
      id: 'avalanche',
      emoji: '🏔️',
      name: '雪山で眠った登山家',
      tag: '頂を目指した挑戦者',
      color: '#94A3B8',
      description: '前世のあなたは、誰も登ったことのない山の頂上を目指した登山家。雪崩に巻き込まれましたが、その挑戦心は永遠に語り継がれます。',
      traits: ['挑戦心', '忍耐力', '孤独を恐れない', '寒さに敏感'],
      advice: '【転生ボーナス】前世の不屈の挑戦心が「どんな困難も諦めない粘り強さ」として活きています。',
      scoreWeights: [0, 0, 2, 0, 1, 0, 0.5],
    },
    {
      id: 'time_loop',
      emoji: '⏳',
      name: '時の狭間に消えた時空旅人',
      tag: '時を超えた旅人',
      color: '#F59E0B',
      description: '前世のあなたは、時空を旅する能力を持つ旅人。ある日、時の狭間に迷い込み、永遠の旅を続けることになりました。',
      traits: ['デジャヴが多い', '同じ夢を見る', '時間に敏感', '既視感'],
      advice: '【転生ボーナス】前世の時空旅行の記憶が「デジャヴや強い直感」として表れています。',
      scoreWeights: [0, 0, 1, 1, 0, 0, 2],
    },
    {
      id: 'phoenix',
      emoji: '🔥',
      name: '炎の中で生まれ変わった不死鳥',
      tag: '永遠の転生者',
      color: '#F97316',
      description: '前世のあなたは、不死鳥と契約を交わした者。炎の中で何度も死に、何度も生まれ変わる運命を持っています。',
      traits: ['復活力', '何度でも立ち上がる', '変化を恐れない', '情熱的'],
      advice: '【転生ボーナス】何度倒れても立ち上がる「不死鳥の魂」が宿っています。挫折は次のステージへの通過儀式です。',
      scoreWeights: [1.5, 0, 0.5, 0.5, 0, 0.5, 1],
    },
    {
      id: 'moonlight',
      emoji: '🌕',
      name: '月明かりの下で消えた巫女',
      tag: '神秘の祈り手',
      color: '#A78BFA',
      description: '前世のあなたは、月の力を借りて人々を癒す巫女。満月の夜、月に召されて天に昇りました。',
      traits: ['神秘的', '癒しの力', '月に惹かれる', '感受性豊か'],
      advice: '【転生ボーナス】前世の癒しの力が「人の心を安らげるオーラ」として受け継がれています。',
      scoreWeights: [0, 1, 0, 1.5, 1, 0, 1],
    },
    {
      id: 'treasure',
      emoji: '💎',
      name: '宝を守り抜いた番人',
      tag: '伝説の守護者',
      color: '#EAB308',
      description: '前世のあなたは、古代の宝物庫を守る番人。最後まで宝を守り通し、そのまま宝と共に封印されました。',
      traits: ['責任感が強い', '約束を守る', '頑固', '大切なものを守る'],
      advice: '【転生ボーナス】前世の守護精神が「大切なものを絶対に守り抜く意志」として表れています。',
      scoreWeights: [0, 0, 0, 0, 0.5, 1.5, 1.5],
    },
  ],

  hashtags: ['前世の死因', '前世診断', '転生ボーナス', '診断研究所'],
  references: [
    'Jung, C. G. (1968). The Archetypes and the Collective Unconscious.',
    'Campbell, J. (1949). The Hero with a Thousand Faces.',
    'Stevenson, I. (1974). Twenty Cases Suggestive of Reincarnation.',
  ],
};
